name: Create cached environment
description: Create cached environment with pip and poetry dev dependencies.

runs:
  using: "composite"

  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Cache environment
      uses: actions/cache@v3
      with:
        path: ~/.cache/pypoetry
        key: ${{ hashFiles('poetry.lock') }}

    - name: Install pip and Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
      shell: bash -l {0}

    - name: Install dependencies
      run: |
        poetry install --with dev
      shell: bash -l {0}
