name: pages

on:
  push:
    paths:
      - '**/pages.yml'
      - 'src/**'
      - 'docs/**'
      - 'poetry.lock'
      - 'pyproject.toml'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create cached environment
        uses: ./.github/actions/create-cached-environment

      - name: Build and deploy to GitHub Pages
        run: |
          poetry run mkdocs gh-deploy --verbose --force
